/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib


open scoped BigOperators

open scoped Real

open scoped Nat

open scoped Classical

open scoped Pointwise

set_option maxHeartbeats 200000

set_option maxRecDepth 3000

set_option synthInstance.maxHeartbeats 20000

set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false

set_option autoImplicit false

noncomputable section

/-
For any unit quaternions $q,k\in S^3$, the geodesic distance satisfies $\dgeo(q,k)=\dgeo(-q,k)=\dgeo(q,-k)$.
-/
noncomputable def s_sim (q k : Quaternion ℝ) : ℝ := |inner ℝ q k|

noncomputable def d_geo (q k : Quaternion ℝ) : ℝ := 2 * Real.arccos (s_sim q k)

lemma sign_invariance (q k : Quaternion ℝ) (_hq : ‖q‖ = 1) (_hk : ‖k‖ = 1) :
  d_geo q k = d_geo (-q) k ∧ d_geo q k = d_geo q (-k) := by
    unfold d_geo;
    unfold s_sim; aesop;

/-
For pure imaginary quaternions $u, v$, the inner product of their exponentials is $\cos\|u\|\cos\|v\| + \text{sinc}(\|u\|)\text{sinc}(\|v\|)\langle u, v\rangle$.
-/
lemma inner_exp_exp_eq (u v : Quaternion ℝ) (hu : u.re = 0) (hv : v.re = 0) :
  inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) =
  Real.cos ‖u‖ * Real.cos ‖v‖ + (if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) * inner ℝ u v := by
    -- Use the formula `exp u = cos ‖u‖ + (sin ‖u‖ / ‖u‖) • u` for pure imaginary quaternions.
    have h_exp : ∀ u : Quaternion ℝ, u.re = 0 → NormedSpace.exp ℝ u = Real.cos ‖u‖ + (if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) • u := by
      -- Use the formula `exp u = cos ‖u‖ + (sin ‖u‖ / ‖u‖) • u` for pure imaginary quaternions. This follows from the definition of the exponential map.
      have h_exp : ∀ u : Quaternion ℝ, u.re = 0 → NormedSpace.exp ℝ u = Real.cos ‖u‖ + (Real.sin ‖u‖ / ‖u‖) • u := by
        exact fun u a ↦ Quaternion.exp_of_re_eq_zero u a;
      by_cases h : ‖u‖ = 0 <;> aesop;
    norm_num [ h_exp u hu, h_exp v hv, inner ];
    by_cases hu' : u = 0 <;> by_cases hv' : v = 0 <;> simp +decide [ *, mul_assoc ];
    ring

/-
For $|x| \le 1$, $|\cos x - (1 - x^2/2)| \le x^4/24$.
-/
lemma cos_approx_bound (x : ℝ) (hx : |x| ≤ 1) :
  |Real.cos x - (1 - x^2 / 2)| ≤ |x|^4 / 24 := by
    -- This follows from the Taylor series expansion of cosine with the Lagrange remainder term.
    have h_cos_taylor_bound : ∀ x : ℝ, |x| ≤ 1 → |Real.cos x - (1 - x^2 / 2)| ≤ |x|^4 / 24 := by
      intro x hx
      have h_cos_taylor : ∀ x : ℝ, 0 ≤ x → x ≤ 1 → |Real.cos x - (1 - x^2 / 2)| ≤ x^4 / 24 := by
        -- This follows from the Taylor series expansion of cosine with the Lagrange remainder term. The 4th derivative of cos is cos, which is bounded by 1. Thus the error is bounded by $|x|^4/4!$.
        intros x hx_nonneg hx_le_one
        have h_cos_taylor : ∀ x : ℝ, 0 ≤ x → x ≤ 1 → Real.cos x ≤ 1 - x^2 / 2 + x^4 / 24 := by
          -- Let's choose any $x$ in the interval $[0, 1]$.
          intro x hx_nonneg hx_le_one
          have h_cos_taylor : ∀ t ∈ Set.Icc 0 x, Real.sin t ≥ t - t^3 / 6 := by
            -- Let's choose any $t$ in the interval $[0, x]$.
            intro t ht
            have h_sin_taylor : ∀ u ∈ Set.Icc 0 t, Real.cos u ≥ 1 - u^2 / 2 := by
              exact fun u a ↦ Real.one_sub_sq_div_two_le_cos;
            -- Integrate both sides of $\cos u \geq 1 - u^2 / 2$ from $0$ to $t$.
            have h_integral : ∫ u in (0 : ℝ)..t, Real.cos u ≥ ∫ u in (0 : ℝ)..t, (1 - u^2 / 2) := by
              refine' intervalIntegral.integral_mono_on _ _ _ _ <;> aesop;
            norm_num at h_integral; linarith;
          -- Integrate both sides of $\sin t \geq t - t^3 / 6$ from $0$ to $x$.
          have h_integral : ∫ t in (0 : ℝ)..x, Real.sin t ≥ ∫ t in (0 : ℝ)..x, (t - t^3 / 6) := by
            refine' intervalIntegral.integral_mono_on _ _ _ _ <;> aesop;
          norm_num at h_integral; linarith;
        -- Since $\cos x$ is decreasing in $[0, 1]$, we have $\cos x \geq 1 - x^2 / 2$.
        have h_cos_lower_bound : ∀ x : ℝ, 0 ≤ x → x ≤ 1 → Real.cos x ≥ 1 - x^2 / 2 := by
          exact fun x a a ↦ Real.one_sub_sq_div_two_le_cos;
        exact abs_le.mpr ⟨ by linarith [ h_cos_lower_bound x hx_nonneg hx_le_one, h_cos_taylor x hx_nonneg hx_le_one ], by linarith [ h_cos_lower_bound x hx_nonneg hx_le_one, h_cos_taylor x hx_nonneg hx_le_one ] ⟩
      cases abs_cases x <;> simp +decide [ * ];
      · exact h_cos_taylor x ( by linarith ) ( by linarith );
      · convert h_cos_taylor ( -x ) ( by linarith ) ( by linarith ) using 1 <;> norm_num;
    exact h_cos_taylor_bound x hx

/-
For $|x| \le 1$, $|\text{sinc}(x) - 1| \le x^2/6$.
-/
lemma sinc_approx_bound (x : ℝ) (hx : |x| ≤ 1) :
  |(if x = 0 then 1 else Real.sin x / x) - 1| ≤ x^2 / 6 := by
    by_cases hx' : x = 0 <;> simp_all +decide;
    -- Since $|x| \le 1$, we have $|\sin x - x| \le \frac{|x|^3}{6}$.
    have h_sin_x_bound : |Real.sin x - x| ≤ |x|^3 / 6 := by
      -- By the properties of the derivative of $\sin x$, we know that $|\sin x - x| \leq \frac{|x|^3}{6}$ for $|x| \leq 1$.
      have h_sin_deriv_bound : ∀ x : ℝ, 0 < x ∧ x ≤ 1 → |Real.sin x - x| ≤ x^3 / 6 := by
        -- By the properties of the derivative of $\sin x$, we know that $|\sin x - x| \leq \frac{|x|^3}{6}$ for $|x| \leq 1$. We'll use the fact that $|\cos x - 1| \leq \frac{x^2}{2}$ for $0 < x \leq 1$.
        have h_cos_bound : ∀ x : ℝ, 0 < x ∧ x ≤ 1 → |Real.cos x - 1| ≤ x^2 / 2 := by
          -- Use the trigonometric identity $\cos x = 1 - 2 \sin^2 (x/2)$ and the fact that $|\sin (x/2)| \leq x/2$ for $0 < x \leq 1$.
          intros x hx
          have h_sin_sq : |Real.sin (x / 2)| ≤ x / 2 := by
            exact le_of_lt ( by rw [ abs_of_nonneg ( Real.sin_nonneg_of_nonneg_of_le_pi ( by linarith ) ( by linarith [ Real.pi_gt_three ] ) ) ] ; exact Real.sin_lt <| by linarith );
          rw [ show Real.cos x - 1 = -2 * Real.sin ( x / 2 ) ^ 2 by rw [ Real.sin_sq, Real.cos_sq ] ; ring_nf ] ; rw [ abs_le ] ; constructor <;> nlinarith [ abs_le.mp h_sin_sq ] ;
        -- Using the fact that $|\cos x - 1| \leq \frac{x^2}{2}$ for $0 < x \leq 1$, we can bound the integral.
        intros x hx
        have h_integral_bound : |∫ t in (0 : ℝ)..x, (Real.cos t - 1)| ≤ ∫ t in (0 : ℝ)..x, t^2 / 2 := by
          rw [ intervalIntegral.integral_of_le hx.1.le, intervalIntegral.integral_of_le hx.1.le ];
          refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( MeasureTheory.integral_mono_of_nonneg _ _ _ );
          · exact Filter.Eventually.of_forall fun _ => norm_nonneg _;
          · exact Continuous.integrableOn_Ioc ( by continuity );
          · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with y hy using h_cos_bound y ⟨ hy.1, hy.2.trans hx.2 ⟩;
        norm_num at *; linarith;
      cases abs_cases x <;> simp +decide [ * ];
      · exact h_sin_deriv_bound x ⟨ lt_of_le_of_ne ( by linarith ) ( Ne.symm hx' ), by linarith ⟩;
      · convert h_sin_deriv_bound ( -x ) ⟨ by linarith, by linarith ⟩ using 1 ; norm_num [ abs_sub_comm ];
        ring_nf;
    field_simp;
    rw [ abs_div ];
    rw [ div_mul_eq_mul_div, div_le_iff₀ ] <;> nlinarith [ abs_pos.mpr hx', abs_mul_abs_self x ]

/-
For $|x|, |y| \le 1$, $|\cos x \cos y - (1 - x^2/2 - y^2/2)| \le x^4 + y^4 + x^2 y^2/2$.
-/
lemma cos_mul_approx (x y : ℝ) (hx : |x| ≤ 1) (hy : |y| ≤ 1) :
  |Real.cos x * Real.cos y - (1 - x^2 / 2 - y^2 / 2)| ≤ |x|^4 + |y|^4 + x^2 * y^2 / 2 := by
    -- We have $\cos x = 1 - x^2/2 + R_x$ with $|R_x| \le x^4/24$ and similarly for $y$.
    have h_cos_approx : ∀ x : ℝ, |x| ≤ 1 → |Real.cos x - (1 - x^2 / 2)| ≤ |x|^4 / 24 := by
      exact cos_approx_bound;
    -- Applying the approximations to our expression and using the triangle inequality:
    have h_cos_approx_prod : |Real.cos x * Real.cos y - (1 - x^2 / 2 - y^2 / 2)| ≤ |Real.cos x - (1 - x^2 / 2)| * |Real.cos y| + |Real.cos y - (1 - y^2 / 2)| * |1 - x^2 / 2| + x^2 * y^2 / 4 := by
      rw [ ← abs_mul, ← abs_mul ];
      convert abs_add_three ( ( Real.cos x - ( 1 - x ^ 2 / 2 ) ) * Real.cos y ) ( ( Real.cos y - ( 1 - y ^ 2 / 2 ) ) * ( 1 - x ^ 2 / 2 ) ) ( x ^ 2 * y ^ 2 / 4 ) using 2 ; ring;
      rw [ abs_of_nonneg ( by positivity ) ];
    refine le_trans h_cos_approx_prod ?_;
    refine' le_trans ( add_le_add_three ( mul_le_of_le_one_right ( abs_nonneg _ ) ( Real.abs_cos_le_one _ ) ) ( mul_le_of_le_one_right ( abs_nonneg _ ) ( abs_le.mpr ⟨ by nlinarith only [ abs_le.mp hx, abs_le.mp hy ], by nlinarith only [ abs_le.mp hx, abs_le.mp hy ] ⟩ ) ) le_rfl ) _;
    refine' le_trans ( add_le_add_three ( h_cos_approx x hx ) ( h_cos_approx y hy ) le_rfl ) _;
    nlinarith only [ show 0 ≤ |x|^4 by positivity, show 0 ≤ |y|^4 by positivity, show 0 ≤ x^2 * y^2 by positivity, show |x|^4 ≤ 1 by exact pow_le_one₀ ( abs_nonneg x ) hx, show |y|^4 ≤ 1 by exact pow_le_one₀ ( abs_nonneg y ) hy ]

/-
For $\|u\|, \|v\| \le 1$, the error in approximating the sinc product term is bounded by $O(\epsilon^4)$.
-/
lemma sinc_mul_approx (u v : Quaternion ℝ) (hu : ‖u‖ ≤ 1) (hv : ‖v‖ ≤ 1) :
  |((if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) - 1) * inner ℝ u v| ≤ (‖u‖^2 / 6 + ‖v‖^2 / 6 + ‖u‖^2 * ‖v‖^2 / 36) * (‖u‖ * ‖v‖) := by
    have h_bound : |((if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) - 1)| ≤ ‖u‖^2 / 6 + ‖v‖^2 / 6 + ‖u‖^2 * ‖v‖^2 / 36 := by
      -- Applying the bound from `sinc_approx_bound` to each term in the product.
      have h_sinc_u : |(if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) - 1| ≤ ‖u‖^2 / 6 := by
        convert sinc_approx_bound ‖u‖ ( abs_le.mpr ⟨ by linarith [ norm_nonneg u ], by linarith [ norm_nonneg u ] ⟩ ) using 1
      have h_sinc_v : |(if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) - 1| ≤ ‖v‖^2 / 6 := by
        convert sinc_approx_bound ‖v‖ ( abs_le.mpr ⟨ by linarith [ norm_nonneg v ], by linarith [ norm_nonneg v ] ⟩ ) using 1;
      rw [ abs_le ] at *;
      constructor <;> nlinarith [ show 0 ≤ ‖u‖ ^ 2 by positivity, show 0 ≤ ‖v‖ ^ 2 by positivity ];
    convert mul_le_mul h_bound ( abs_real_inner_le_norm u v ) ( by positivity ) ( by positivity ) using 1 ; norm_num [ abs_mul ]

/-
The error in approximating the inner product of exponentials by $1 - \|u-v\|^2/2$ is bounded by the sum of the errors from the cosine and sinc approximations.
-/
lemma inner_expansion_combine (u v : Quaternion ℝ) (hu : u.re = 0) (hv : v.re = 0) (hu_norm : ‖u‖ ≤ 1) (hv_norm : ‖v‖ ≤ 1) :
  |inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) - (1 - ‖u - v‖^2 / 2)| ≤
  |‖u‖^4 + ‖v‖^4 + ‖u‖^2 * ‖v‖^2 / 2| + (‖u‖^2 / 6 + ‖v‖^2 / 6 + ‖u‖^2 * ‖v‖^2 / 36) * (‖u‖ * ‖v‖) := by
    -- We have `inner (exp u) (exp v) = cos|u|cos|v| + sinc|u|sinc|v|<u,v>`.
    have h_exp_inner : inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) = Real.cos ‖u‖ * Real.cos ‖v‖ + (if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) * inner ℝ u v := by
      exact inner_exp_exp_eq u v hu hv;
    -- Recall that $1 - \|u-v\|^2/2 = 1 - (\|u\|^2 + \|v\|^2 - 2\langle u, v \rangle)/2 = (1 - \|u\|^2/2 - \|v\|^2/2) + \langle u, v \rangle$.
    have h_norm_eq : 1 - ‖u - v‖^2 / 2 = (1 - ‖u‖^2 / 2 - ‖v‖^2 / 2) + inner ℝ u v := by
      norm_num [ norm_sub_sq_real, hu, hv ] ; ring;
    -- Apply the triangle inequality to the expression.
    have h_triangle : |(Real.cos ‖u‖ * Real.cos ‖v‖ - (1 - ‖u‖^2 / 2 - ‖v‖^2 / 2)) + ((if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) - 1) * inner ℝ u v| ≤ |Real.cos ‖u‖ * Real.cos ‖v‖ - (1 - ‖u‖^2 / 2 - ‖v‖^2 / 2)| + |((if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) * (if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) - 1) * inner ℝ u v| := by
      exact
        abs_add_le (Real.cos ‖u‖ * Real.cos ‖v‖ - (1 - ‖u‖ ^ 2 / 2 - ‖v‖ ^ 2 / 2))
          ((((if ‖u‖ = 0 then 1 else Real.sin ‖u‖ / ‖u‖) *
                if ‖v‖ = 0 then 1 else Real.sin ‖v‖ / ‖v‖) -
              1) *
            inner ℝ u v);
    convert h_triangle.trans ( add_le_add ( cos_mul_approx _ _ ( show |‖u‖| ≤ 1 by rw [ abs_of_nonneg ( norm_nonneg u ) ] ; exact hu_norm ) ( show |‖v‖| ≤ 1 by rw [ abs_of_nonneg ( norm_nonneg v ) ] ; exact hv_norm ) |> le_trans <| ?_ ) ( sinc_mul_approx _ _ hu_norm hv_norm ) ) using 1;
    · exact congr_arg _ ( by rw [ h_exp_inner, h_norm_eq ] ; ring );
    · norm_num [ abs_of_nonneg, add_nonneg, sq_nonneg, mul_nonneg ];
      exact le_abs_self _

/-
For $x \in [0, 1]$, $|\arccos(x)^2 - 2(1-x)| \le C(1-x)^2$.
-/
lemma arccos_sq_approx :
  ∃ C > 0, ∀ x : ℝ, 0 ≤ x → x ≤ 1 → |Real.arccos x ^ 2 - 2 * (1 - x)| ≤ C * (1 - x) ^ 2 := by
    -- Let's choose the constant $C = 16$.
    use 166; norm_num;
    -- Let $x = \cos \theta$ with $\theta \in [0, \pi/2]$.
    intro x hx_nonneg hx_le_one
    set θ : ℝ := Real.arccos x
    have hθ_range : 0 ≤ θ ∧ θ ≤ Real.pi / 2 := by
      exact ⟨ Real.arccos_nonneg _, by rw [ Real.arccos_le_pi_div_two ] ; linarith ⟩;
    -- We want $|\theta^2 - 4\sin^2(\theta/2)| \le C (2\sin^2(\theta/2))^2 = 4C \sin^4(\theta/2)$.
    suffices h_sin_approx : ∀ θ : ℝ, 0 ≤ θ ∧ θ ≤ Real.pi / 2 → |θ^2 - 4 * Real.sin (θ / 2)^2| ≤ 166 * (2 * Real.sin (θ / 2)^2)^2 by
      convert h_sin_approx θ hθ_range using 2 <;> norm_num [ Real.sin_sq, Real.cos_sq ] ; ring_nf;
      · rw [ Real.cos_arccos ] <;> linarith;
      · rw [ mul_div_cancel₀ _ two_ne_zero, Real.cos_arccos ] <;> linarith;
    -- For $\theta \in [0, \pi/2]$, we have $\sin(\theta/2) \leq \theta/2$ and $\sin(\theta/2) \geq \theta/2 - (\theta/2)^3 / 6$.
    have h_sin_bounds : ∀ θ : ℝ, 0 ≤ θ ∧ θ ≤ Real.pi / 2 → Real.sin (θ / 2) ≤ θ / 2 ∧ Real.sin (θ / 2) ≥ θ / 2 - (θ / 2)^3 / 6 := by
      intros θ hθ_range
      have h_sin_le : Real.sin (θ / 2) ≤ θ / 2 := by
        rcases eq_or_lt_of_le hθ_range.1 with ( rfl | hθ_pos ) <;> [ norm_num; exact le_of_lt ( Real.sin_lt <| by linarith ) ]
      have h_sin_ge : Real.sin (θ / 2) ≥ θ / 2 - (θ / 2)^3 / 6 := by
        -- Utilize the known inequality for the sine function: $\sin(x) \geq x - \frac{x^3}{6}$ for $0 \leq x \leq \frac{\pi}{2}$.
        have h_sin_ineq : ∀ x : ℝ, 0 ≤ x ∧ x ≤ Real.pi / 2 → Real.sin x ≥ x - x^3 / 6 := by
          -- Let's choose any $x \in [0, \frac{\pi}{2}]$ and derive the inequality.
          intro x hx_range
          have h_sin_deriv : ∀ t ∈ Set.Icc 0 x, Real.cos t ≥ 1 - t^2 / 2 := by
            exact fun t a ↦ Real.one_sub_sq_div_two_le_cos;
          -- Integrate both sides of $\cos t \geq 1 - t^2 / 2$ from $0$ to $x$.
          have h_integral : ∫ t in (0 : ℝ)..x, Real.cos t ≥ ∫ t in (0 : ℝ)..x, (1 - t^2 / 2) := by
            refine' intervalIntegral.integral_mono_on _ _ _ _ <;> aesop;
          norm_num at h_integral; linarith;
        grind
      exact ⟨h_sin_le, h_sin_ge⟩;
    intro θ hθ_range
    have h_sin_sq_bounds : Real.sin (θ / 2)^2 ≤ (θ / 2)^2 ∧ Real.sin (θ / 2)^2 ≥ (θ / 2 - (θ / 2)^3 / 6)^2 := by
      exact ⟨ pow_le_pow_left₀ ( Real.sin_nonneg_of_nonneg_of_le_pi ( by linarith ) ( by linarith ) ) ( h_sin_bounds θ hθ_range |>.1 ) 2, pow_le_pow_left₀ ( by nlinarith [ Real.pi_le_four, pow_nonneg hθ_range.1 2, pow_nonneg hθ_range.1 3 ] ) ( h_sin_bounds θ hθ_range |>.2 ) 2 ⟩;
    rw [ abs_le ] ; constructor <;> nlinarith [ pow_nonneg hθ_range.1 3, pow_nonneg hθ_range.1 4, pow_nonneg hθ_range.1 5, pow_nonneg hθ_range.1 6, Real.pi_le_four ] ;

/-
The deviation of the inner product from 1 is bounded by $O(\varepsilon^2)$.
-/
lemma inner_deviation_bound :
  ∃ C > 0, ∀ ε > 0, ε < 1 →
  ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε →
  |1 - inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v)| ≤ C * ε ^ 2 := by
    -- We have `inner (exp u) (exp v) \approx 1 - ||u-v||^2/2`.
    have h_inner_approx : ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) - (1 - ‖u - v‖^2 / 2)| ≤ ε^4 + ε^4 + ε^4 / 2 + (ε^2 / 6 + ε^2 / 6 + ε^4 / 36) * ε^2 := by
      intros ε hε_pos hε_lt_1 u v hu hv hu_norm hv_norm
      have h_inner_approx : |inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) - (1 - ‖u - v‖^2 / 2)| ≤ |‖u‖^4 + ‖v‖^4 + ‖u‖^2 * ‖v‖^2 / 2| + (‖u‖^2 / 6 + ‖v‖^2 / 6 + ‖u‖^2 * ‖v‖^2 / 36) * (‖u‖ * ‖v‖) := by
        convert inner_expansion_combine u v hu hv ( show ‖u‖ ≤ 1 by linarith ) ( show ‖v‖ ≤ 1 by linarith ) using 1;
      refine le_trans h_inner_approx ?_;
      refine' add_le_add _ _;
      · rw [ abs_of_nonneg ( by positivity ) ];
        nlinarith only [ show 0 ≤ ‖u‖ ^ 2 * ‖v‖ ^ 2 by positivity, show 0 ≤ ‖u‖ ^ 4 by positivity, show 0 ≤ ‖v‖ ^ 4 by positivity, show ‖u‖ ^ 2 ≤ ε ^ 2 by nlinarith only [ hu_norm, norm_nonneg u ], show ‖v‖ ^ 2 ≤ ε ^ 2 by nlinarith only [ hv_norm, norm_nonneg v ] ];
      · gcongr;
        · nlinarith only [ show 0 ≤ ‖u‖ * ‖v‖ by positivity, show ‖u‖ * ‖v‖ ≤ ε ^ 2 by nlinarith only [ norm_nonneg u, norm_nonneg v, hu_norm, hv_norm ], hu_norm, hv_norm ];
        · nlinarith [ norm_nonneg u, norm_nonneg v ];
    -- Since `||u-v|| \le ||u|| + ||v|| \le 2\epsilon`, `||u-v||^2/2 \le 2\epsilon^2`.
    have h_norm_diff : ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → ‖u - v‖^2 / 2 ≤ 2 * ε^2 := by
      exact fun ε hε₁ hε₂ u v hu hv hu' hv' => by nlinarith [ norm_nonneg ( u - v ), show ‖u - v‖ ≤ ε + ε by exact le_trans ( norm_sub_le _ _ ) ( add_le_add hu' hv' ) ] ;
    refine' ⟨ 8 + 8 + 8 / 2 + ( 8 / 6 + 8 / 6 + 8 / 36 ) * 8, by norm_num, fun ε hε₁ hε₂ u v hu hv hu' hv' => _ ⟩;
    rw [ abs_sub_comm ];
    have := abs_le.mp ( h_inner_approx ε hε₁ hε₂ u v hu hv hu' hv' );
    cases abs_cases ( Inner.inner ℝ ( NormedSpace.exp ℝ u ) ( NormedSpace.exp ℝ v ) - 1 ) <;> nlinarith [ pow_pos hε₁ 3, pow_pos hε₁ 4, pow_pos hε₁ 5, pow_pos hε₁ 6, pow_pos hε₁ 7, pow_pos hε₁ 8, h_norm_diff ε hε₁ hε₂ u v hu hv hu' hv' ]

/-
The squared geodesic distance is approximately $8(1 - \langle q, k \rangle)$, with error $O(\varepsilon^4)$.
-/
lemma d_geo_sq_approx_linear :
  ∃ C > 0, ∀ ε > 0, ε < 1 →
  ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε →
  |d_geo (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) ^ 2 - 8 * (1 - inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))| ≤ C * ε ^ 4 := by
    -- By combining the results from `arccos_sq_approx` and `inner_deviation_bound`, we can bound the deviation of the squared geodesic distance from $8(1 - \langle q, k \rangle)$.
    have h_combined : ∃ C > 0, ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |Real.arccos (abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))) ^ 2 - 2 * (1 - abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v)))| ≤ C * ε ^ 4 := by
      -- Applying the bounds from `arccos_sq_approx` and `inner_deviation_bound`, we can bound the deviation of the squared geodesic distance from $8(1 - \langle q, k \rangle)$.
      obtain ⟨C₁, hC₁⟩ : ∃ C₁ > 0, ∀ x : ℝ, 0 ≤ x → x ≤ 1 → |Real.arccos x ^ 2 - 2 * (1 - x)| ≤ C₁ * (1 - x) ^ 2 := by
        exact arccos_sq_approx;
      -- Applying the bounds from `inner_deviation_bound`, we can bound the deviation of the inner product from 1.
      obtain ⟨C₂, hC₂⟩ : ∃ C₂ > 0, ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |1 - abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))| ≤ C₂ * ε ^ 2 := by
        -- Applying the bounds from `inner_deviation_bound`, we can bound the deviation of the inner product from 1. Since $|1 - x| \leq |1 - x|$ for any $x$, we can use the same constant $C₂$.
        obtain ⟨C₂, hC₂⟩ : ∃ C₂ > 0, ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |1 - inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v)| ≤ C₂ * ε ^ 2 := by
          exact inner_deviation_bound;
        refine' ⟨ C₂, hC₂.1, fun ε hε₁ hε₂ u v hu hv hu' hv' => _ ⟩;
        refine' le_trans _ ( hC₂.2 ε hε₁ hε₂ u v hu hv hu' hv' );
        cases abs_cases ( Inner.inner ℝ ( NormedSpace.exp ℝ u ) ( NormedSpace.exp ℝ v ) ) <;> cases abs_cases ( 1 - |Inner.inner ℝ ( NormedSpace.exp ℝ u ) ( NormedSpace.exp ℝ v )| ) <;> cases abs_cases ( 1 - Inner.inner ℝ ( NormedSpace.exp ℝ u ) ( NormedSpace.exp ℝ v ) ) <;> linarith;
      refine' ⟨ 8 * C₁ * C₂ ^ 2 + 1, by nlinarith, fun ε hε₁ hε₂ u v hu hv hu' hv' => _ ⟩;
      refine' le_trans ( hC₁.2 _ _ _ ) _;
      · positivity;
      · have h_inner_bound : ∀ u v : Quaternion ℝ, ‖u‖ = 1 → ‖v‖ = 1 → |inner ℝ u v| ≤ 1 := by
          exact fun u v hu hv => by simpa [ hu, hv ] using abs_real_inner_le_norm u v;
        convert h_inner_bound ( ‖NormedSpace.exp ℝ u‖⁻¹ • NormedSpace.exp ℝ u ) ( ‖NormedSpace.exp ℝ v‖⁻¹ • NormedSpace.exp ℝ v ) _ _ using 1 <;> norm_num [ norm_smul, hu, hv ];
      · -- Applying the bound from `inner_deviation_bound`, we get:
        have h_inner_bound : |1 - abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))| ≤ C₂ * ε ^ 2 := by
          exact hC₂.2 ε hε₁ hε₂ u v hu hv hu' hv';
        -- Squaring both sides of the inequality $|1 - |inner| \leq C₂ * ε²|$, we get $(1 - |inner|)^2 \leq (C₂ * ε²)^2$.
        have h_sq : (1 - abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v)))^2 ≤ (C₂ * ε^2)^2 := by
          simpa [ sq_abs ] using pow_le_pow_left₀ ( abs_nonneg _ ) h_inner_bound 2;
        nlinarith [ show 0 ≤ C₁ * ε ^ 4 by exact mul_nonneg hC₁.1.le ( by positivity ) ];
    obtain ⟨ C, hC₀, hC ⟩ := h_combined;
    -- We need to show that $|8(1 - |x|) - 8(1 - x)| \le O(\varepsilon^4)$.
    have h_abs : ∃ C > 0, ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |8 * (1 - abs (inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))) - 8 * (1 - inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v))| ≤ C * ε ^ 4 := by
      -- By `inner_deviation_bound`, $|1 - x| \le C \varepsilon^2$. So $(1-x)^2 \le C^2 \varepsilon^4$.
      obtain ⟨ C', hC'₀, hC' ⟩ : ∃ C' > 0, ∀ ε > 0, ε < 1 → ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε → |1 - inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v)| ≤ C' * ε ^ 2 := by
        exact inner_deviation_bound;
      -- If $x \ge 0$, then $|x| = x$, so the LHS is zero.
      use 8 * C'^2;
      refine' ⟨ by positivity, fun ε hε₁ hε₂ u v hu hv hu' hv' => abs_le.mpr ⟨ _, _ ⟩ ⟩ <;> cases abs_cases ( Inner.inner ℝ ( NormedSpace.exp ℝ u ) ( NormedSpace.exp ℝ v ) ) <;> nlinarith [ abs_le.mp ( hC' ε hε₁ hε₂ u v hu hv hu' hv' ), show 0 ≤ C' * ε ^ 2 by positivity ];
    obtain ⟨ C', hC'₀, hC' ⟩ := h_abs;
    refine' ⟨ 8 * C + C', by positivity, fun ε hε₁ hε₂ u v hu hv hu' hv' => _ ⟩;
    unfold d_geo;
    unfold s_sim;
    exact abs_le.mpr ⟨ by nlinarith [ abs_le.mp ( hC ε hε₁ hε₂ u v hu hv hu' hv' ), abs_le.mp ( hC' ε hε₁ hε₂ u v hu hv hu' hv' ) ], by nlinarith [ abs_le.mp ( hC ε hε₁ hε₂ u v hu hv hu' hv' ), abs_le.mp ( hC' ε hε₁ hε₂ u v hu hv hu' hv' ) ] ⟩

/-
The inner product of exponentials is approximately $1 - \|u-v\|^2/2$ with error $O(\varepsilon^4)$.
-/
lemma inner_approx :
  ∃ C > 0, ∀ ε > 0, ε < 1 →
  ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε →
  |inner ℝ (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) - (1 - ‖u - v‖ ^ 2 / 2)| ≤ C * ε ^ 4 := by
    -- By combining the results from `inner_expansion_combine` and `inner_deviation_bound`, we get the desired inequality.
    use (8 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ) + (1 : ℝ);
    refine' ⟨ by norm_num, fun ε hε₁ hε₂ u v hu hv hu' hv' => _ ⟩;
    refine' le_trans ( inner_expansion_combine u v hu hv ( hu'.trans hε₂.le ) ( hv'.trans hε₂.le ) ) _;
    refine' le_trans ( add_le_add ( show |‖u‖ ^ 4 + ‖v‖ ^ 4 + ‖u‖ ^ 2 * ‖v‖ ^ 2 / 2| ≤ ε ^ 4 + ε ^ 4 + ε ^ 2 * ε ^ 2 / 2 by rw [ abs_of_nonneg ( by positivity ) ] ; gcongr ) ( show ( ‖u‖ ^ 2 / 6 + ‖v‖ ^ 2 / 6 + ‖u‖ ^ 2 * ‖v‖ ^ 2 / 36 ) * ( ‖u‖ * ‖v‖ ) ≤ ( ε ^ 2 / 6 + ε ^ 2 / 6 + ε ^ 2 * ε ^ 2 / 36 ) * ( ε * ε ) by gcongr ) ) _;
    nlinarith [ pow_pos hε₁ 3, pow_pos hε₁ 4, pow_pos hε₁ 5, pow_pos hε₁ 6, pow_pos hε₁ 7, pow_pos hε₁ 8, pow_pos hε₁ 9, pow_pos hε₁ 10 ]

/-
Let $u,v\in\R^3$ with $\|u\|,\|v\|\le \varepsilon$ and $\varepsilon$ below the injectivity radius, and define $q=\exp(u)$, $k=\exp(v)$ in $\Spin(3)$. Then there exists $C>0$ (depending only on the Lie bracket constants) such that $|\dgeo(q,k)^2 - 4\|u-v\|^2| \le C\,\varepsilon^4$.
-/
lemma small_angle_expansion :
  ∃ C > 0, ∀ ε > 0, ε < 1 →
  ∀ u v : Quaternion ℝ, u.re = 0 → v.re = 0 → ‖u‖ ≤ ε → ‖v‖ ≤ ε →
  |d_geo (NormedSpace.exp ℝ u) (NormedSpace.exp ℝ v) ^ 2 - 4 * ‖u - v‖ ^ 2| ≤ C * ε ^ 4 := by
    -- By the triangle inequality:
    -- \[
    -- |\dgeo(q,k)^2 - 4\|u-v\|^2| \le |\dgeo(q,k)^2 - 8(1 - \text{inner})| + |8(1 - \text{inner}) - 4\|u-v\|^2|
    -- \]
    -- We already have bounds for both terms on the right-hand side.
    obtain ⟨C₁, hC₁⟩ := d_geo_sq_approx_linear;
    obtain ⟨C₂, hC₂⟩ := inner_approx;
    use C₁ + 8 * C₂;
    exact ⟨ by linarith, fun ε hε₁ hε₂ u v hu hv hu' hv' => abs_le.mpr ⟨ by linarith [ abs_le.mp ( hC₁.2 ε hε₁ hε₂ u v hu hv hu' hv' ), abs_le.mp ( hC₂.2 ε hε₁ hε₂ u v hu hv hu' hv' ) ], by linarith [ abs_le.mp ( hC₁.2 ε hε₁ hε₂ u v hu hv hu' hv' ), abs_le.mp ( hC₂.2 ε hε₁ hε₂ u v hu hv hu' hv' ) ] ⟩ ⟩
